// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
const isSupabaseConfigured = Boolean(
  SUPABASE_URL &&
    SUPABASE_PUBLISHABLE_KEY &&
    !SUPABASE_URL.includes("<your-project-ref>") &&
    !SUPABASE_PUBLISHABLE_KEY.includes("<your-anon-key>")
);

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

function createNoopSupabaseClient() {
  return {
    auth: {
      onAuthStateChange: () => ({ data: { subscription: { unsubscribe: () => {} } } }),
      getSession: async () => ({ data: { session: null } }),
      signUp: async () => ({ error: new Error("Supabase is not configured") }),
      signInWithPassword: async () => ({ error: new Error("Supabase is not configured") }),
      signOut: async () => ({ error: null }),
    },
    from: () => ({
      select: async () => ({ data: null, error: new Error("Supabase is not configured") }),
      insert: async () => ({ data: null, error: new Error("Supabase is not configured") }),
      delete: async () => ({ data: null, error: new Error("Supabase is not configured") }),
      eq: () => ({
        select: async () => ({ data: null, error: new Error("Supabase is not configured") }),
        order: async () => ({ data: null, error: new Error("Supabase is not configured") }),
        delete: async () => ({ data: null, error: new Error("Supabase is not configured") }),
      }),
      order: async () => ({ data: null, error: new Error("Supabase is not configured") }),
      single: async () => ({ data: null, error: new Error("Supabase is not configured") }),
    }),
    storage: {
      from: () => ({
        upload: async () => ({ data: null, error: new Error("Supabase is not configured") }),
        getPublicUrl: () => ({ data: { publicUrl: "" } }),
      }),
    },
  } as any;
}

export const supabase = isSupabaseConfigured
  ? createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
      },
    })
  : createNoopSupabaseClient();

export { isSupabaseConfigured };